.TH "rpmrebuild" "1" "1.4.5" "Eric Gerbier" "rpm tools"
.SH "NAME"
.LP 
rpmrebuild \- a tool to build an rpm package from an installed package
.SH "SYNOPSIS"
.LP 
rpmrebuild [\fIoption\fP] <\fIpackagename\fP>
.br 
or
.br 
rpm \-\-rpmrebuild [\fIoption\fP] <\fIpackagename\fP>
.SH "DESCRIPTION"
.LP 
rpmrebuild is a tool to build easily rpm package.
it can be used to build an rpm file from an installed package (lost rpm) or to quickly make change to a package : just have your change on installed files and call rpmrebuild.
.SH "OPTIONS"
.LP 
.TP 
\fB\-a|\-\-additional\fP <\fIflags\fP>
pass additional flags to rpmbuild
.TP 
\fB\-b|\-\-batch\fP
work in batch mode (no interactive query if files change)
.TP 
\fB\-c|\-\-comment\-missing\fP <\fIyes\fP|\fIno\fP>
comment out in the specfile missing files. Default \fBno\fP. This flag is meanful only when \fB\-\-verify\fP is \fBno\fP.
.TP 
\fB\-D|\-\-define\fP <\fIdefines\fP>
defines to be passed to rpmbuild.
.TP 
\fB\-d|\-\-directory\fP <\fIdirectory\fP>
rpm package result will be written in  <\fIdirectory\fP>.
.TP 
\fB\-e|\-\-edit\-spec\fP
open the generated specfile with your favorite editor before rpm build
.TP 
\fB\-f|\-\-filter\fP <\fIfile\fP>
.LP 
\fB\-f|\-\-filter\fP <\fI"file arguments"\fP>
.br 
apply an externel filter to the specfile before rpm build (see below PLUGINS). if more than one filter is called, they are concateneted.
.TP 
\fB\-h|\-\-help\fP
Output help information and exit.
.TP 
\fB\-k|\-\-keep\-perm|\-\-pug\-from\-fs\fP
keep installed files permission, uid and gid (do not force to orginal files permission, uid and gid saved in rpm database)
.TP 
\fB\-m|\-\-modify\fP <\fIscript\fP>
can be used only with \fB\-\-package\fP option. After rpm package converted
to cpio and unpackaged invoked script \fB<script>\fP to change unpacked files.
This script got \fBRPM_BUILD_ROOT\fP environment variable pointed to the
unpacked files root directory.
.TP 
\fB\-p|\-\-package\fP
use package file, not installed rpm (this option is like rpm's \-p option)
.TP 
\fB\-P|\-\-autoprovide\fP
use rpm scripts to compute provides
.TP 
\fB\-R|\-\-autorequire\fP
use rpm scripts to compute requires
.TP 
\fB\-\-pug\-from\-db (default)\fP
set files permission, uid and gid as saved in rpm database
.TP 
\fB\-s|\-\-spec\-only\fP <\fIspecfile\fP>
do not rebuild package. only generate specfile.
.TP 
\fB\-v|\-\-verbose\fP
verbose output
.TP 
\fB\-V|\-\-version\fP
Output version information and exit.
.TP 
\fB\-w|\-\-warning\fP
display some warnings if it detects a potential problem (for example, spec file which contains filename with globbing char).
.TP 
\fB\-y|\-\-verify\fP <\fIyes\fP|\fIno\fP>
Turn on/off package verifing before processing. Default \fByes\fP. Can be turn off to get better performance.
.SH "FILES"
.LP 
.TP 
\fB~/.rpmmacros\fP 
is used by rpm when building packages (macros)
.TP 
\fB/etc/popt\fP
contains rpm alias used by rpmrebuild
.SH "ENVIRONMENT"
.LP 
.TP 
\fBTMPDIR\fP
Directory for temporal files. If not set /tmp is used.
.TP 
\fBVISUAL\fP
used to specify an editor for specfile. if not set \fBEDITOR\fP variable examined.
.TP 
\fBEDITOR\fP
used to specify an editor for specfile. if not set \fBvi\fP used.
.TP 
\fBRPM_BUILD_ROOT\fP
ROOT of unpacked files. Passed to script invoked with \fB\-\-modify\fP
.SH "PLUGINS"
.LP 
rpmrebuild use may be extended with plugins, via the "\-\-filter" option.
.LP 
plugins are searched in PATH, then on /usr/lib/rpmrebuild/plugins
.br 
A plugin receive on STDIN the generated specfile, make any changes, and rewrite it on STDOUT.
.TP 
An example is given in rpmrebuild package with file2pac.plugin, which transform all rpm dependencies in package dependencies (dependencies to file are hard to resolve when updating a system).

For example, it change
.br 
Requires: /bin/sh
.br 
Requires: libc.so.6(GLIBC_2.1)
.br 

into :
.br 
Requires: bash
.br 
Requires: glibc
.SH "EXAMPLES"
.LP 
Build an rpm package as closed as possible to original one:
.LP 
\fBrpm \-\-rpmrebuild \-\-batch package\fP
.LP 
Build a modified package:
.LP 
\fBrpm \-\-rpmrebuild \-\-keep\-perm package\fP
.LP 
Build a rpm from another rpm file:
.LP 
\fBrpm \-\-rpmrebuild \-\-package \-\-filter filter /usr/src/redhat/i386/package\-i386.rpm\fP
.LP 
Rebuild rpm as legacy (rpm[23]) package:
.LP 
\fBrpm \-\-rpmrebuild \-\-additional "\-\-nodirtokens" bash\fP
.LP 
Specify generated rpm name:
.LP 
\fBrpm \-\-rpmrebuild \-\-define "_rpmfilename %%{NAME}.rpm" bash\fP
.LP 
Change package interactive
.LP 
\fBrpm \-\-rpmrebuild \-\-package \-\-modify "/bin/bash" /some/place/bash.rpm\fP
.LP 
Change package non\-interactive
.LP 
\fBrpm \-\-rpmrebuild \-\-package \-\-modify "a.sh && b.sh" /some/place/bash.rpm\fP
.LP 
if you have problem with rpm building, and if you know specfile syntax, you can also edit it:
.LP 
\fBrpm \-\-rpmrebuild  \-\-edit\-spec package\fP
.SH "AUTHORS"
.LP 
Eric Gerbier <gerbier@users.sourceforge.net>
.br 
Valery Reznic <valery_reznic@users.sourceforge.net>
.TP 
See <URL:http://rpmrebuild.sourceforge.net/>.
.SH "NOTES"
.LP 
.TP 
rpmrebuild can not reproduce exactly a package, so
.br 
\- md5 checksum will not match original ones.
.br 
\- gpg or pgp signatures are lost

.TP 
packages which contains file with globbing caracteres (* .. ? ) will not build
.SH "COPYRIGHT"
.LP 
rpmrebuild is copyright © 2002 by Eric Gerbier.
.br 
this program is distributed under GNU General Public License
.br 
It is provided "as is", without any express or implied
warranties.  See the file COPYING for details.
.SH "SEE ALSO"
.LP 
rpm(8), rpmbuild(8)
