.TH "rpmrebuild" "1" "1.2.1" "Eric Gerbier" "rpm tools"
.SH "NAME"
.LP 
rpmrebuild \- a tool to build an rpm package from an installed package
.SH "SYNTAX"
.LP 
rpmrebuild [\fIoption\fP] <\fIpackagename\fP>
.br 
or
.br 
rpm \-\-rpmrebuild [\fIoption\fP] <\fIpackagename\fP>
.SH "DESCRIPTION"
.LP 
rpmrebuild is a tool to build easily rpm package.
it can be used to build an rpm file from an installed package (lost rpm) or to quickly make change to a package : just have your change on installed files and call rpmrebuild.
.SH "OPTIONS"
.LP 
.TP 
\fB\-b|\-\-batch\fR
work in batch mode (no interactive query if files change)
.TP 
\fB\-d|\-\-dir\fR <\fIdirectory\fP>
rpm package result will be written in  <\fIdirectory\fP>.
.TP 
\fB\-e|\-\-edit\-spec\fR
open the generated specfile with your favorite editor before rpm build
.TP 
\fB\-k|\-\-keep\-perm|\-\-pug\-from\-fs\fR
keep installed files permission, uid and gid (do not force to orginal files permission, uid and gid saved in rpm database)
.TP 
\fB\-\-pug\-from\-db (default)\fR
set files permission, uid and gid as saved in rpm database
.TP 
\fB\-h|\-\-help\fR
Output help information and exit.
.TP 
\fB\-r|\-\-resolv\-dep\fR
change file dependencies in package dependencies.
.TP 
\fB\-s|\-\-spec\-only\fR <\fIspecfile\fP>
do not rebuild package. only generate specfile.
.TP 
\fB\-v|\-\-verbose\fR
verbose output
.TP 
\fB\-V|\-\-version\fR
Output version information and exit.
.SH "FILES"
.LP 
\fI~/.rpmmacros\fP 
\fI/etc/popt\fP 
.br 
.SH "ENVIRONMENT VARIABLES"
.LP 
.TP 
\fBVISUAL\fP
used to specify an editor for specfile
.TP 
\fBEDITOR\fP
used to specify an editor for specfile
.SH "EXAMPLES"
.LP 
To build an rpm package as closed as possible to original one:
.LP 
rpm \-\-rpmrebuid \-\-batch package 
.LP 
to build a modified package :
.LP 
rpm \-\-rpmrebuild \-\-keep\-perm package
.LP 
if you have problem with rpm building, and if you know specfile syntax, you can also edit it:
.LP 
rpm \-\-rpmrebuild  \-\-edit\-spec package
.SH "AUTHORS"
.LP 
Eric Gerbier <gerbier@users.sourceforge.net>
.br 
Valery Reznic <valery_reznic@users.sourceforge.net>
.SH "SEE ALSO"
.LP 
rpm(8)
